version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-stretch-node
        environment:
          BUNDLER_VERSION: 2.1.4
          RAILS_ENV: test
    steps:
      - checkout
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - run:
          name: Database Setup
          command: |
            bin/rails db:schema:load --trace 
      - run:
          name: Run Test
          command: bundle exec rspec --format progress --format RspecJunitFormatter --out /tmp/test-results/rspec.xml --format html --out /tmp/test-results/rspec.html
      - store_test_results:
          path: /tmp/test-results
